SupportTrackPRO.WebMVC/Controllers/CustomerController.cs
using Microsoft.AspNet.Identity;
using SupportTrackPRO.Data;
using SupportTrackPRO.Models;
using SupportTrackPRO.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SupportTrackPRO.WebMVC.Controllers
{
    [Authorize]
    public class CustomerController : Controller
    {

        public bool VerifyMyUserRole(string myUserRole)
        {
            bool isInRole = User.IsInRole(myUserRole);
            return isInRole;
        }

        public int ReturnMySupportCompanyId()
        {
            string myUserName = User.Identity.Name;

            var tempctx = new ApplicationDbContext();
            int mySupportCompanyId = tempctx.SupportProviders.Where(c => c.UserName == myUserName).Select(c => c.SupportCompanyId).FirstOrDefault();

            return mySupportCompanyId;
        }

        public string ReturnMySupportCompanyName()
        {
            string myUserName = User.Identity.Name;

            var tempctx = new ApplicationDbContext();
            int mySupportCompanyId = tempctx.SupportProviders.Where(c => c.UserName == myUserName).Select(c => c.SupportCompanyId).FirstOrDefault();
            string mySupportCompanyName = tempctx.SupportCompanies.Where(c => c.SupportCompanyId == mySupportCompanyId).Select(c => c.CompanyName).FirstOrDefault();

            return mySupportCompanyName;
        }

        public Guid ReturnApplicationUserId()
        {
            return Guid.Parse(User.Identity.GetUserId());
        }

        public int ReturnMyCustomerId()
        {
            var tempctx = new ApplicationDbContext();
            Guid userId = Guid.Parse(User.Identity.GetUserId());
            int myCustomerId = tempctx.Customers.Where(c => c.ApplicationUserId == userId).Select(c => c.CustomerId).FirstOrDefault();

            return myCustomerId;
        }

        public bool VerifyCustomerExists(Guid applicationUserId)
        {
            var existingCustomer = new Customer { ApplicationUserId = applicationUserId };

            using (var tempCustomerDbContext = new ApplicationDbContext())
            {
                var query = tempCustomerDbContext.Customers.Where(c => c.ApplicationUserId == applicationUserId).Select(c => c.ApplicationUserId).FirstOrDefault();
                if (query == applicationUserId)
                {
                    return true;
                }
                return false;
            }
        }

        //
        // Returns bool depending on if the customer record was added or not
        // based on the current users ApplicationUserId.
        //
        public bool UpdateCustomerDb(Guid applicationUserId)
        {
            var newCustomer = new Customer { ApplicationUserId = applicationUserId };
            if (VerifyCustomerExists(applicationUserId) == false)
            {
                using (var tempCustomerDbContext = new ApplicationDbContext())
                {
                    tempCustomerDbContext.Customers.Add(newCustomer);
                    int wasAdded = tempCustomerDbContext.SaveChanges();
                    if (wasAdded == 1)
                    {
                        return true;
                    }
                }
            }
            return false;
        }

        // GET: Customer
        public ActionResult Index()
        {
            UpdateCustomerDb(ReturnApplicationUserId());

            int mySupportCompanyId = ReturnMySupportCompanyId();
            string mySupportCompanyName = ReturnMySupportCompanyName();
            int myCustomerId = ReturnMyCustomerId();

            ViewBag.mySupportCompanyId = mySupportCompanyId;
            ViewBag.mySupportCompanyName = mySupportCompanyName;
            ViewBag.myCustomerId = myCustomerId;

            var userId = Guid.Parse(User.Identity.GetUserId());
            var service = new CustomerService(userId, ReturnMySupportCompanyId());
            var model = service.GetCustomers();

            return View(model);
        }

        public ActionResult Create()
        {
            UpdateCustomerDb(ReturnApplicationUserId());
            int mySupportCompanyId = ReturnMySupportCompanyId();
            string mySupportCompanyName = ReturnMySupportCompanyName();
            int myCustomerId = ReturnMyCustomerId();

            ViewBag.mySupportCompanyId = mySupportCompanyId;
            ViewBag.mySupportCompanyName = mySupportCompanyName;
            ViewBag.myCustomerId = myCustomerId;

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CustomerCreate model)
        {
            UpdateCustomerDb(ReturnApplicationUserId());
            int mySupportCompanyId = ReturnMySupportCompanyId();
            string mySupportCompanyName = ReturnMySupportCompanyName();
            int myCustomerId = ReturnMyCustomerId();

            ViewBag.mySupportCompanyId = mySupportCompanyId;
            ViewBag.mySupportCompanyName = mySupportCompanyName;
            ViewBag.myCustomerId = myCustomerId;

            if (!ModelState.IsValid)
            {
                return View(model);
            }
            var userId = Guid.Parse(User.Identity.GetUserId());
            var service = new CustomerService(userId, mySupportCompanyId);

            service.CreateCustomer(model,mySupportCompanyId);

            return RedirectToAction("Index");
        }

        public ActionResult Details(int id)
        {
            UpdateCustomerDb(ReturnApplicationUserId());
            int mySupportCompanyId = ReturnMySupportCompanyId();
            string mySupportCompanyName = ReturnMySupportCompanyName();
            int myCustomerId = ReturnMyCustomerId();

            ViewBag.mySupportCompanyId = mySupportCompanyId;
            ViewBag.mySupportCompanyName = mySupportCompanyName;
            ViewBag.myCustomerId = myCustomerId;

            var userId = Guid.Parse(User.Identity.GetUserId());
            var svc = new CustomerService(userId, ReturnMySupportCompanyId());

            var model = svc.GetCustomerByCustomerId(id);

            return View(model);
        }

        public ActionResult Edit(int id)
        {
            UpdateCustomerDb(ReturnApplicationUserId());
            int mySupportCompanyId = ReturnMySupportCompanyId();
            string mySupportCompanyName = ReturnMySupportCompanyName();
            int myCustomerId = ReturnMyCustomerId();

            ViewBag.mySupportCompanyId = mySupportCompanyId;
            ViewBag.mySupportCompanyName = mySupportCompanyName;
            ViewBag.myCustomerId = myCustomerId;

            var userId = Guid.Parse(User.Identity.GetUserId());
            var service = new CustomerService(userId, mySupportCompanyId);

            var detail = service.GetCustomerDetailByCustomerId(id);
            var model = new CustomerEdit
            {
                CustomerId = detail.CustomerId,
                ApplicationUserId = detail.ApplicationUserId,
                FirstName = detail.FirstName,
                LastName = detail.LastName,
                Address1 = detail.Address1,
                Address2 = detail.Address2,
                City = detail.City,
                State = detail.State,
                ZipCode = detail.ZipCode,
                PhoneNumber1 = detail.PhoneNumber1,
                PhoneNumber2 = detail.PhoneNumber2
            };
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, CustomerEdit model)
        {
            UpdateCustomerDb(ReturnApplicationUserId());
            int mySupportCompanyId = ReturnMySupportCompanyId();
            string mySupportCompanyName = ReturnMySupportCompanyName();
            int myCustomerId = ReturnMyCustomerId();

            ViewBag.mySupportCompanyId = mySupportCompanyId;
            ViewBag.mySupportCompanyName = mySupportCompanyName;
            ViewBag.myCustomerId = myCustomerId;

            if (!ModelState.IsValid) return View(model);

            if (model.CustomerId != id)
            {
                ModelState.AddModelError("", "Id Mismatch");
                return View(model);
            }
            var userId = Guid.Parse(User.Identity.GetUserId());
            var service = new CustomerService(userId, ReturnMySupportCompanyId());

            if (service.UpdateCustomer(model, userId))
            {
                TempData["SaveResult"] = "Updated.";
                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", "Not updated.");
            return View(model);
        }
    }


}

SupportTrackPRO.WebMVC/Controllers/SupportCompanyController.cs
using Microsoft.AspNet.Identity;
using SupportTrackPRO.Data;
using SupportTrackPRO.Models;
using SupportTrackPRO.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SupportTrackPRO.WebMVC.Controllers
{
    [Authorize]
    public class SupportCompanyController : Controller
    {
        public bool VerifyMyUserRole(string myUserRole)
        {
            Guid userId = Guid.Parse(User.Identity.GetUserId());
            bool isInRole = User.IsInRole(myUserRole);
            return isInRole;
        }

        public int ReturnMySupportCompanyId()
        {
            Guid userId = Guid.Parse(User.Identity.GetUserId());
            string myUserName = User.Identity.Name;

            var tempctx = new ApplicationDbContext();
            int mySupportCompanyId = tempctx.SupportProviders.Where(c => c.UserName == myUserName).Select(c => c.SupportCompanyId).FirstOrDefault();

            return mySupportCompanyId;
        }

        public string ReturnMySupportCompanyName()
        {
            string myUserName = User.Identity.Name;

            var tempctx = new ApplicationDbContext();
            int mySupportCompanyId = tempctx.SupportProviders.Where(c => c.UserName == myUserName).Select(c => c.SupportCompanyId).FirstOrDefault();
            string mySupportCompanyName = tempctx.SupportCompanies.Where(c => c.SupportCompanyId == mySupportCompanyId).Select(c => c.CompanyName).FirstOrDefault();

            return mySupportCompanyName;
        }

        public int ReturnMyCustomerId()
        {
            string myUserName = User.Identity.Name;

            var tempctx = new ApplicationDbContext();
            int myCustomerId = tempctx.Customers.Where(c => c.ApplicationUserId == Guid.Parse(User.Identity.GetUserId())).Select(c => c.CustomerId).FirstOrDefault();

            return myCustomerId;
        }

        // GET: SupportCompany
        public ActionResult Index()
        {
            var userId = Guid.Parse(User.Identity.GetUserId());
            var service = new SupportCompanyService(userId,ReturnMySupportCompanyId());
            var model = service.GetSupportCompanies();

            return View(model);
        }

        public ActionResult Create()
        {
            int mySupportCompanyId = ReturnMySupportCompanyId();
            string mySupportCompanyName = ReturnMySupportCompanyName();

            ViewBag.mySupportCompanyId = mySupportCompanyId;
            ViewBag.mySupportCompanyName = mySupportCompanyName;

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(SupportCompanyCreate model)
        {


            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var userId = Guid.Parse(User.Identity.GetUserId());
            int mySupportCompanyId = ReturnMySupportCompanyId();
            var service = new SupportCompanyService(userId, mySupportCompanyId);

            service.CreateSupportCompany(model);

            return RedirectToAction("Index");
        }

    }

}

SupportTrackPRO.WebMVC/Controllers/SupportProductController.cs
using Microsoft.AspNet.Identity;
using SupportTrackPRO.Data;
using SupportTrackPRO.Models;
using SupportTrackPRO.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SupportTrackPRO.WebMVC.Controllers
{
    [Authorize]
    public class SupportProductController : Controller
    {

        public bool VerifyMyUserRole(string myUserRole)
        {
            bool isInRole = User.IsInRole(myUserRole);
            return isInRole;
        }

        public int ReturnMySupportCompanyId()
        {
            string myUserName = User.Identity.Name;

            var tempctx = new ApplicationDbContext();
            int mySupportCompanyId = tempctx.SupportProviders.Where(c => c.UserName == myUserName).Select(c => c.SupportCompanyId).FirstOrDefault();

            return mySupportCompanyId;
        }

        public string ReturnMySupportCompanyName()
        {
            string myUserName = User.Identity.Name;

            var tempctx = new ApplicationDbContext();
            int mySupportCompanyId = tempctx.SupportProviders.Where(c => c.UserName == myUserName).Select(c => c.SupportCompanyId).FirstOrDefault();
            string mySupportCompanyName = tempctx.SupportCompanies.Where(c => c.SupportCompanyId == mySupportCompanyId).Select(c => c.CompanyName).FirstOrDefault();

            return mySupportCompanyName;
        }

        // GET: SupportProduct
        public ActionResult Index()
        {
            var userId = Guid.Parse(User.Identity.GetUserId());
            var service = new SupportProductService(userId, ReturnMySupportCompanyId());
            var model = service.GetSupportProducts(User.Identity.Name, ReturnMySupportCompanyId());

            return View(model);
        }

        public ActionResult Create()
        {
            int mySupportCompanyId = ReturnMySupportCompanyId();
            string mySupportCompanyName = ReturnMySupportCompanyName();

            ViewBag.mySupportCompanyId = mySupportCompanyId;
            ViewBag.mySupportCompanyName = mySupportCompanyName;

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(SupportProductCreate model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var userId = Guid.Parse(User.Identity.GetUserId());
            int mySupportCompanyId = ReturnMySupportCompanyId();
            var service = new SupportProductService(userId, mySupportCompanyId);

            service.CreateSupportProduct(model,mySupportCompanyId);

            return RedirectToAction("Index");
        }
    }


}

SupportTrackPRO.WebMVC/Controllers/SupportProviderController.cs
using Microsoft.AspNet.Identity;
using SupportTrackPRO.Data;
using SupportTrackPRO.Models;
using SupportTrackPRO.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SupportTrackPRO.WebMVC.Controllers
{
    [Authorize]
    public class SupportProviderController : Controller
    {

        public bool VerifyMyUserRole(string myUserRole)
        {
            bool isInRole = User.IsInRole(myUserRole);
            return isInRole;
        }

        public int ReturnMySupportCompanyId()
        {
            string myUserName = User.Identity.Name;

            var tempctx = new ApplicationDbContext();
            int mySupportCompanyId = tempctx.SupportProviders.Where(c => c.UserName == myUserName).Select(c => c.SupportCompanyId).FirstOrDefault();

            return mySupportCompanyId;
        }

        public string ReturnMySupportCompanyName()
        {
            string myUserName = User.Identity.Name;

            var tempctx = new ApplicationDbContext();
            int mySupportCompanyId = tempctx.SupportProviders.Where(c => c.UserName == myUserName).Select(c => c.SupportCompanyId).FirstOrDefault();
            string mySupportCompanyName = tempctx.SupportCompanies.Where(c => c.SupportCompanyId == mySupportCompanyId).Select(c => c.CompanyName).FirstOrDefault();

            return mySupportCompanyName;
        }

        // GET: SupportProvider
        public ActionResult Index()
        {
            var userId = Guid.Parse(User.Identity.GetUserId());
            var service = new SupportProviderService(userId, ReturnMySupportCompanyId());
            var model = service.GetSupportProviders(User.Identity.Name, ReturnMySupportCompanyId());

            return View(model);
        }

        public ActionResult Create()
        {
            int mySupportCompanyId = ReturnMySupportCompanyId();
            string mySupportCompanyName = ReturnMySupportCompanyName();

            ViewBag.mySupportCompanyId = mySupportCompanyId;
            ViewBag.mySupportCompanyName = mySupportCompanyName;

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(SupportProviderCreate model)
        {

            if (!ModelState.IsValid)
            {
                return View(model);
            }

            int mySupportCompanyId = ReturnMySupportCompanyId();
            var userId = Guid.Parse(User.Identity.GetUserId());
            var service = new SupportProviderService(userId, mySupportCompanyId);

            service.CreateSupportProvider(model, mySupportCompanyId);

            return RedirectToAction("Index");
        }

    }



}

SupportTrackPRO.WebMVC/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p></p>

SupportTrackPRO.WebMVC/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

SupportTrackPRO.WebMVC/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Support Track PRO - Home";
}

<div class="jumbotron">
    <h1>Support Track PRO</h1>
    <hr />
    <p>SupportTrackPRO is a subscribable service for small companies that have products that have warranties that they have to service.</p>
    <hr />
    @if (User.Identity.IsAuthenticated)
    {
        <p>Welcome @User.Identity.Name!!!</p>

        <p><a href="@Url.Action("Support", "Home")" class="btn btn-primary btn-lg">Go To Support &raquo;</a></p>
    }
    else
    {
        <p class="lead">Please Click One Of The Following</p>
        <h4>If you're a support provider, or a customer seeking support on a product, login below.</h4>

        <p><a href="@Url.Action("Login", "Account")" class="btn btn-primary btn-lg btn-stpro-home">Login &raquo;</a></p>
        <h4>If you're a new customer seeking warranty support on a product, please register below.</h4>
        <p><a href="@Url.Action("Register", "Account")" class="btn btn-primary btn-lg btn-stpro-home">Customer Registration &raquo;</a></p>
        <h4>If you're a company seeing to subscribe to the SupportTrackPRO support platform to provide support to your customers, click below.</h4>
        <p><a href="https://asp.net" class="btn btn-primary btn-lg btn-stpro-home">Support Company Subscription &raquo;</a></p>
    }
</div>

<!--

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>
-->

SupportTrackPRO.WebMVC/Views/Home/Support.cshtml
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>ViewBag.Title = "SupportTrackPRO"</title>
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
        <link rel="stylesheet" href="~/Content/Site.css"

    </head>
    <body>
        <div class="jumbotron">
            <h1>Support Options</h1>
            @if (User.Identity.IsAuthenticated)
            {
                if ((User.IsInRole("SupportTrackPROAdmin") == true) || (User.IsInRole("SupportManager")) == true)
                {

                    <hr />
                    <p class="lead">Support Track PRO Site Subscription Administrator Only</p>
                    <br />
                    <p><a href="@Url.Action("Create", "SupportCompany")" class="btn btn-primary btn-lg">Create Company &raquo;</a></p>
                    <p><a href="@Url.Action("Index", "SupportCompany")" class="btn btn-primary btn-lg">List Company &raquo;</a></p>

                    <hr />
                    <p class="lead">Support Manager Only</p>
                    <br />
                    <p><a href="@Url.Action("Create", "SupportProduct")" class="btn btn-primary btn-lg">Create Products &raquo;</a></p>
                    <p><a href="@Url.Action("Index", "SupportProduct")" class="btn btn-primary btn-lg">List Products &raquo;</a></p>
                    <p><a href="@Url.Action("Create", "SupportProvider")" class="btn btn-primary btn-lg">Create Providers &raquo;</a></p>
                    <p><a href="@Url.Action("Index", "SupportProvider")" class="btn btn-primary btn-lg">List Providers &raquo;</a></p>

                    <p><a href="@Url.Action("Update", "SupportCompany")" class="btn btn-primary btn-lg">Update Company Information &raquo;</a></p>
                    <p><a href="@Url.Action("Register", "Account")" class="btn btn-primary btn-lg">Register Support Manager/Provider/Customer &raquo;</a></p>

                }

                if ((User.IsInRole("SupportTrackPROAdmin")) || (User.IsInRole("SupportManager")) || (User.IsInRole("SupportProvider")))
                {
                    <hr />
                    <p class="lead">Support Manager/Provider Only</p>
                    <br />
                    <p><a href="@Url.Action("Support", "Home")" class="btn btn-primary btn-lg">Tickets &raquo;</a></p>
                    <p><a href="@Url.Action("Support", "Home")" class="btn btn-primary btn-lg">Warrenties &raquo;</a></p>
                    <p><a href="@Url.Action("Support", "Home")" class="btn btn-primary btn-lg">Customers &raquo;</a></p>
                }

                if ((User.IsInRole("SupportTrackPROAdmin")) || (User.IsInRole("SupportManager")) || (User.IsInRole("SupportProvider")) || (User.IsInRole("SupportCustomer")))
                {
                    <hr />
                    <p class="lead">Customer Product Support</p>
                    <br />
                    <p><a href="@Url.Action("Index", "Customer")" class="btn btn-primary btn-lg btn-stpro-home">Update My User Profile &raquo;</a></p>
                    <p><a href="@Url.Action("Create", "RegisteredWarranty")" class="btn btn-primary btn-lg btn-stpro-home">Register A Product Warrenty &raquo;</a></p>
                    <p><a href="@Url.Action("Create", "SupportTicket")" class="btn btn-primary btn-lg btn-stpro-home">Support Requests - Create New &raquo;</a></p>
                    <p><a href="@Url.Action("Index", "SupportTicket")" class="btn btn-primary btn-lg btn-stpro-home">Support Requests - Status &raquo;</a></p>
                }
            }
        </div>
    </body>
</html>